name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: php-actions/composer@v6

    - name: Build
      run: |
        composer install

    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}